name: "clip_text"
platform: "tensorrt_plan"
max_batch_size: 8

input [
  {
    name: "input_text"
    data_type: TYPE_INT32
    dims: [77]
  }
]

output [
  {
    name: "text_features"
    data_type: TYPE_FP32
    dims: [512]
  }
]
